apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
spec:
  template:
    spec:
      containers:
      - name: demo-frontend
        image: 674050571849.dkr.ecr.ap-northeast-2.amazonaws.com/app:${IMAGE_TAG}

