apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 674050571849.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newName: 674050571849.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml

