apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 674050571849.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newName: 674050571849.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newTag: 5c93ae5b
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: demo-frontend
- path: service-patch.yaml
  target:
    kind: Service
    name: demo-frontend
