---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: 674050571849.dkr.ecr.ap-northeast-2.amazonaws.com/app:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
